inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: disable

Metrics/AbcSize:
  Exclude:
    - 'lib/views/**/*'

Metrics/MethodLength:
  Exclude:
    - 'lib/views/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/views/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/views/**/*'

Style/HashSyntax:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*'
