inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'loaders/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'utils/views/**/*'

Metrics/MethodLength:
  Exclude:
    - 'utils/views/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'utils/views/**/*'

Style/HashSyntax:
  Exclude:
    - '/**/*'
