:language: en
:editor: code
:debugger: pry
:theme:
  :tags:
    :h1:
      - "\e[38;2;227;64;107m\e[1m"
      - "\e[m"
    :h2:
      - "\e[38;2;136;57;239m"
      - "\e[m"
    :hl:
      - "\e[38;2;114;135;253m"
      - "\e[m"
    :disabled:
      - "\e[38;2;121;121;121m"
      - "\e[m"
    :success:
      - "\e[38;2;64;160;43m"
      - "\e[m"
    :warning:
      - "\e[38;2;223;142;29m"
      - "\e[m"
    :fail:
      - "\e[38;2;210;15;57m"
      - "\e[m"
    :string:
      - "\e[38;2;223;142;29m"
      - "\e[m"
    :br:
      - "\n"
  :tables:
    :space_linebroken: true
    :padding: 1
    :corners:
      :top_right: ┌
      :top_left: ┐
      :bottom_right: └
      :bottom_left: ┘
    :straight:
      :vertical: │
      :horizontal: ─
    :junctions:
      :top: ┬
      :middle: ┼
      :bottom: ┴


