name: Pipeline
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.2.0
    steps:
      - uses: actions/checkout@v3
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec rspec spec
  rubocop:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.2.0
    steps:
      - uses: actions/checkout@v3
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec rubocop -f markdown --raise-cop-error postwoman **/*.rb >> $GITHUB_STEP_SUMMARY
